### PR TITLE
Support Apache Kyuubi as built-in datasource

### PR DESCRIPTION
**Pull request by pan3793**
Support of [Apache Kyuubi](https://kyuubi.apache.org/) was added to DBeaver at https://github.com/dbeaver/dbeaver/pull/16559, and now I propose to add Kyuubi as a built-in data source of CloudBeaver.

Kyuubi already uses CloudBeaver to build a public online playground https://try.kyuubi.cloud/, it has run well for several years.

Kyuubi JDBC driver is derived from Hive JDBC driver, but we reworked a lot to make it light and powerful.

I saw there was an issue https://github.com/dbeaver/cloudbeaver/issues/312 about adding Hive JDBC driver as built-in, but the maintainers are concerned about the size and dependencies of the Hive JDBC jar.

Kyuubi JDBC resolved those issues, 

- The size of [kyuubi-hive-jdbc-shaded-1.9.0.jar](https://repo1.maven.org/maven2/org/apache/kyuubi/kyuubi-hive-jdbc-shaded/1.8.1/kyuubi-hive-jdbc-shaded-1.8.1.jar) is 19MB.
- The jar is an all-in-one artifact, all third-party classes have been relocated to `org.apache.kyuubi` package, so there are no class conflict issues.
- It's compatible w/ Kyuubi, Spark Thrift Server, and Hive Server2, including Zookeeper-based HA, and Kerberos features.

For maintainers testing, Kyuubi provides a docker compose based playground[1] to quickly launch a Kyuubi deployment w/ TPC-DS dataset, and documentation[2] on how to use DBeaver to connect to Kyuubi.

[1] https://github.com/apache/incubator-kyuubi/tree/master/docker/playground
[2] https://kyuubi.readthedocs.io/en/master/client/bi_tools/dbeaver.html

### CODE REVIEW

**Comment by pan3793** [comment]
I don't have the permission to access the Jenkins, could any member help me to check why it fails?

**Comment by pan3793** [comment]
@serge-rider I sincerely hope the CloudBeaver community can consider this integration.

I have been asked several times by users from the Apache Kyuubi community about how to use CloudBeaver to access Kyuubi service, and as a temporary solution, I created a [forked repo](https://github.com/pan3793/cloudbeaver) to provide that, would appreciate it if it can be adopted upstream :)

**Comment by cfmcgrady** [comment]
+1 for this

**Comment by cxzl25** [comment]
+1 for this

**Comment by SteNicholas** [comment]
+1. Kyuubi support makes sense to me.

**Comment by bowenliang123** [comment]
+1

**Comment by serge-rider** [comment]
Agreed 👍

**Review by yaooqinn — APPROVED** [review]

**Comment by EvgeniaBzzz** [comment]
@pan3793 
The most recent version of the driver has 4 open CVEs. Unfortunately, in its current form we cannot include it in the product.
For now, you can [add it yourself](https://github.com/dbeaver/cloudbeaver/wiki/Adding-new-database-drivers).

**Comment by pan3793** [comment]
@EvgeniaBzzz

> The most recent version of the driver has 4 open CVEs.

Where can I find the list?

I'm one of the maintainers of [org.apache.kyuubi/kyuubi-hive-jdbc-shaded](https://mvnrepository.com/artifact/org.apache.kyuubi/kyuubi-hive-jdbc-shaded/1.8.1), and we haven't received CVE reports yet.

If you have security-related concerns about publicly discussing the details of an unfixed CVE, please send messages to mailto:private@kyuubi.apache.org

**Comment by EvgeniaBzzz** [comment]
@pan3793 
You can find it on [Maven repository](https://mvnrepository.com/artifact/org.apache.kyuubi/kyuubi-hive-jdbc/1.8.1)

**Comment by LonwoLonwo** [comment]
Thanks for the update @pan3793

**Comment by pan3793** [comment]
@EvgeniaBzzz @LonwoLonwo The Apache Kyuubi 1.9.0 just release now, we have addressed all known CVEs, the latest JDBC Driver available in [Maven Central](https://mvnrepository.com/artifact/org.apache.kyuubi/kyuubi-hive-jdbc/1.9.0) has no CVE warnings too.

**Review by LonwoLonwo — APPROVED** [review]

**Comment by pan3793** [comment]
Kindly ping @EvgeniaBzzz @alexander-skoblikov ~

**Comment by EvgeniaBzzz** [comment]
Hi @pan3793! 
We plan to integrate it during two weeks

**Comment by pan3793** [comment]
@EvgeniaBzzz thank you for the information!

**Review by yagudin10 — APPROVED** [review]

**Comment by pan3793** [comment]
thank you, @yagudin10

**Comment by pan3793** [comment]
@alexander-skoblikov thank you, and everyone!

**Comment by LonwoLonwo** [comment]
Thank you for your contribution and your patience!

**Pull request merged**
