### PR TITLE
Update trino driver to 438

### LINKED ISSUE #2451: Update Trino driver.
We want to update the Trino driver version.

First of all, this update is to address and resolve compatibility issues that have arisen with the latest Trino installations.

### PR DESCRIPTION
**Pull request by alaturqua**
**Summary**
This PR updates the Trino dependency from its current version to version 438. The primary goal of this update is to address and resolve compatibility issues that have arisen with Trino installations, specifically for versions 429 and above.

**Background**
We have identified that the version of the Trino driver currently utilized within cloudbeaver project does not function optimally with Trino version 429 and later. This has led to users experiencing problems due to the incompatibilities between the older driver version and newer versions of Trino installations. The specifics of these issues include runtime errors and failures in connectivity, impacting the overall user experience and the reliability of our project when used in conjunction with these versions of Trino.

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @alaturqua 

Sorry for the late response. Could you please add more info to the PR description? Reasons to update Trino driver?

**Comment by alaturqua** [comment]
Hello @LonwoLonwo,

I initiated the PR to update the Trino dependency to version 438 to address compatibility issues with Trino installations newer than current dependency version 422, specifically version 429 and above. Users of our project who are on Trino 429 or later have encountered problems due to incompatibilities with the older Trino driver version we currently utilize. Although I don't have the exact error messages handy at this moment, the motivation for this update is to ensure broader compatibility and stability with recent Trino versions, enhancing user experience and avoiding potential runtime issues.

**Comment by LonwoLonwo** [comment]
Thanks for the answer @alaturqua and for the clear description.

**Review by LonwoLonwo — APPROVED** [review]

**Comment by LonwoLonwo** [comment]
Thank you for your contribution and your patience!

**Pull request merged**
