### PR TITLE
Environment variable called "CLOUDBEAVER_ROOT_URI" in cloudbeaver.conf

### LINKED ISSUE #2864: Ability to configure the server property rootURI
We want to add an ability to configure the server property "rootURI" with an environment variable to simplify changing its value in dockerized environments.

### PR DESCRIPTION
**Pull request by arioko**
Inclusion of the ability to configure the server property "rootURI" with an environment variable called "CLOUDBEAVER_ROOT_URI" to simplify changing its value in dockenized environments.

### CODE REVIEW

**Comment by LonwoLonwo** [comment]
Hello @arioko 

Thanks for your contribution. We will look at it.

**Comment by LonwoLonwo** [comment]
I will create a ticket for this PR. And a ticket on our internal Jiira board to add this change to our PRO products.

**Review by DenisSinelnikov — APPROVED** [review]
Thank you :)

**Comment by LonwoLonwo** [comment]
Again, thanks for your contribution.
Your changes will be available in the 24.2.0 release.

**Pull request merged**
